name: CodyLHall
favicon: null
layout_spectrum: 1
typography_spectrum: 0.91968
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.09339609113521874
  lightness: 0.4536829637363553
  saturation: 0.016818382078781724
  rhythmicContrast: 0.39039426296949387
purpose: []
